package main

import (
    "errors"
    "fmt"
)

[f1:Number(arg)]: Number {
    if (arg == 42) {
        error "can't work with 42"
    }

    return (arg + 3)
}

ArgError {
    arg:  Number
    prob: String
}

[errorString:ArgError] {
    return "${e.arg} - ${e.prob}"
}

[f2:Number(arg)]: Number {
    if (arg == 42) {
        error ArgError{
            arg: arg
            prop: "can't work with it"
        }
    }

    return (arg + 3)
}

[main] {
    for i in #(7, 42) {
        r = [f1:i]
    }
}

func main() {

    for _, i := range []int{7, 42} {
        if r, e := f1(i); e != nil {
            fmt.Println("f1 failed:", e)
        } else {
            fmt.Println("f1 worked:", r)
        }
    }
    for _, i := range []int{7, 42} {
        if r, e := f2(i); e != nil {
            fmt.Println("f2 failed:", e)
        } else {
            fmt.Println("f2 worked:", r)
        }
    }

    _, e := f2(42)
    if ae, ok := e.(*argError); ok {
        fmt.Println(ae.arg)
        fmt.Println(ae.prob)
    }
}